<?php
/**
 * StationCurrentState
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Leap Play
 *
 * Learn more at https://www.leap-play.com
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.5
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\models;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * StationCurrentState Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class StationCurrentState implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'StationCurrentState';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'station_id' => 'string',
        'display_name' => 'string',
        'control_mode' => 'string',
        'network_state' => 'string',
        'session' => '\Swagger\Client\models\Session'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'station_id' => 'uuid',
        'display_name' => null,
        'control_mode' => null,
        'network_state' => null,
        'session' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'station_id' => 'stationId',
        'display_name' => 'displayName',
        'control_mode' => 'controlMode',
        'network_state' => 'networkState',
        'session' => 'session'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'station_id' => 'setStationId',
        'display_name' => 'setDisplayName',
        'control_mode' => 'setControlMode',
        'network_state' => 'setNetworkState',
        'session' => 'setSession'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'station_id' => 'getStationId',
        'display_name' => 'getDisplayName',
        'control_mode' => 'getControlMode',
        'network_state' => 'getNetworkState',
        'session' => 'getSession'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const CONTROL_MODE_UNDEFINED = 'Undefined';
    const CONTROL_MODE_LOCAL = 'Local';
    const CONTROL_MODE_REMOTE = 'Remote';
    const CONTROL_MODE_REMOTE_WITH_QR_CODE = 'RemoteWithQrCode';
    const NETWORK_STATE_DISCONNECTED = 'Disconnected';
    const NETWORK_STATE_CONNECTING = 'Connecting';
    const NETWORK_STATE_CONNECTED = 'Connected';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getControlModeAllowableValues()
    {
        return [
            self::CONTROL_MODE_UNDEFINED,
            self::CONTROL_MODE_LOCAL,
            self::CONTROL_MODE_REMOTE,
            self::CONTROL_MODE_REMOTE_WITH_QR_CODE,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getNetworkStateAllowableValues()
    {
        return [
            self::NETWORK_STATE_DISCONNECTED,
            self::NETWORK_STATE_CONNECTING,
            self::NETWORK_STATE_CONNECTED,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['station_id'] = isset($data['station_id']) ? $data['station_id'] : null;
        $this->container['display_name'] = isset($data['display_name']) ? $data['display_name'] : null;
        $this->container['control_mode'] = isset($data['control_mode']) ? $data['control_mode'] : null;
        $this->container['network_state'] = isset($data['network_state']) ? $data['network_state'] : null;
        $this->container['session'] = isset($data['session']) ? $data['session'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getControlModeAllowableValues();
        if (!is_null($this->container['control_mode']) && !in_array($this->container['control_mode'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'control_mode', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getNetworkStateAllowableValues();
        if (!is_null($this->container['network_state']) && !in_array($this->container['network_state'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'network_state', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets station_id
     *
     * @return string
     */
    public function getStationId()
    {
        return $this->container['station_id'];
    }

    /**
     * Sets station_id
     *
     * @param string $station_id station_id
     *
     * @return $this
     */
    public function setStationId($station_id)
    {
        $this->container['station_id'] = $station_id;

        return $this;
    }

    /**
     * Gets display_name
     *
     * @return string
     */
    public function getDisplayName()
    {
        return $this->container['display_name'];
    }

    /**
     * Sets display_name
     *
     * @param string $display_name display_name
     *
     * @return $this
     */
    public function setDisplayName($display_name)
    {
        $this->container['display_name'] = $display_name;

        return $this;
    }

    /**
     * Gets control_mode
     *
     * @return string
     */
    public function getControlMode()
    {
        return $this->container['control_mode'];
    }

    /**
     * Sets control_mode
     *
     * @param string $control_mode control_mode
     *
     * @return $this
     */
    public function setControlMode($control_mode)
    {
        $allowedValues = $this->getControlModeAllowableValues();
        if (!is_null($control_mode) && !in_array($control_mode, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'control_mode', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['control_mode'] = $control_mode;

        return $this;
    }

    /**
     * Gets network_state
     *
     * @return string
     */
    public function getNetworkState()
    {
        return $this->container['network_state'];
    }

    /**
     * Sets network_state
     *
     * @param string $network_state network_state
     *
     * @return $this
     */
    public function setNetworkState($network_state)
    {
        $allowedValues = $this->getNetworkStateAllowableValues();
        if (!is_null($network_state) && !in_array($network_state, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'network_state', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['network_state'] = $network_state;

        return $this;
    }

    /**
     * Gets session
     *
     * @return \Swagger\Client\models\Session
     */
    public function getSession()
    {
        return $this->container['session'];
    }

    /**
     * Sets session
     *
     * @param \Swagger\Client\models\Session $session session
     *
     * @return $this
     */
    public function setSession($session)
    {
        $this->container['session'] = $session;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


