<?php
/**
 * SessionLogTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Leap Play
 *
 * Learn more at https://www.leap-play.com
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.5
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SessionLogTest Class Doc Comment
 *
 * @category    Class
 * @description SessionLog
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SessionLogTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SessionLog"
     */
    public function testSessionLog()
    {
    }

    /**
     * Test attribute "station_id"
     */
    public function testPropertyStationId()
    {
    }

    /**
     * Test attribute "session_id"
     */
    public function testPropertySessionId()
    {
    }

    /**
     * Test attribute "requested_by"
     */
    public function testPropertyRequestedBy()
    {
    }

    /**
     * Test attribute "latest_state"
     */
    public function testPropertyLatestState()
    {
    }

    /**
     * Test attribute "started_utc"
     */
    public function testPropertyStartedUtc()
    {
    }

    /**
     * Test attribute "reference"
     */
    public function testPropertyReference()
    {
    }

    /**
     * Test attribute "max_duration_limit"
     */
    public function testPropertyMaxDurationLimit()
    {
    }

    /**
     * Test attribute "ended_utc"
     */
    public function testPropertyEndedUtc()
    {
    }

    /**
     * Test attribute "stopped_by"
     */
    public function testPropertyStoppedBy()
    {
    }

    /**
     * Test attribute "change_requests"
     */
    public function testPropertyChangeRequests()
    {
    }
}
