<?php
/**
 * AccountsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Leap Play
 *
 * Learn more at https://www.leap-play.com
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.5
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * AccountsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AccountsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for changePassword
     *
     * Changes the Password and provides a new Refresh Token (Auth).
     *
     */
    public function testChangePassword()
    {
    }

    /**
     * Test case for confirmEmail
     *
     * Confirms ownership of an E-Mail Address by an E-Mail Confirmation Token.
     *
     */
    public function testConfirmEmail()
    {
    }

    /**
     * Test case for register
     *
     * Registers a User Account.
     *
     */
    public function testRegister()
    {
    }

    /**
     * Test case for requestPassword
     *
     * Receives a Reset Token that is required to reset the Password.
     *
     */
    public function testRequestPassword()
    {
    }

    /**
     * Test case for resendEMailConfirmation
     *
     * Re-sends a message with a EMail Confirmation Token..
     *
     */
    public function testResendEMailConfirmation()
    {
    }

    /**
     * Test case for resetPassword
     *
     * Resets the Password with an Reset Token.
     *
     */
    public function testResetPassword()
    {
    }
}
