<?php
/**
 * StationsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Leap Play
 *
 * Learn more at https://www.leap-play.com
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.5
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * StationsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class StationsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createStation
     *
     * Creates a Station (Auth).
     *
     */
    public function testCreateStation()
    {
    }

    /**
     * Test case for getSessionLogsAll
     *
     * Gets closed Sessions from all stations (Auth).
     *
     */
    public function testGetSessionLogsAll()
    {
    }

    /**
     * Test case for getSessionLogsByStationId
     *
     * Gets closed Sessions (Auth).
     *
     */
    public function testGetSessionLogsByStationId()
    {
    }

    /**
     * Test case for getSettings
     *
     * Gets the Settings of all Stations (Auth).
     *
     */
    public function testGetSettings()
    {
    }

    /**
     * Test case for getSettingsByStationId
     *
     * Get the Settings of an Station (Auth).
     *
     */
    public function testGetSettingsByStationId()
    {
    }

    /**
     * Test case for getState
     *
     * Get the Station's State (Auth).
     *
     */
    public function testGetState()
    {
    }

    /**
     * Test case for getStates
     *
     * Gets Collection of Station States (Auth).
     *
     */
    public function testGetStates()
    {
    }

    /**
     * Test case for sessionCreate
     *
     * Creates a Session (Auth).
     *
     */
    public function testSessionCreate()
    {
    }

    /**
     * Test case for sessionStop
     *
     * Stops the running Session (Auth).
     *
     */
    public function testSessionStop()
    {
    }

    /**
     * Test case for sessionUpdate
     *
     * Updates the running Session. (Auth).
     *
     */
    public function testSessionUpdate()
    {
    }

    /**
     * Test case for setSettings
     *
     * Sets the Settings for an Station (Auth).
     *
     */
    public function testSetSettings()
    {
    }

    /**
     * Test case for setStationMode
     *
     * Sets the Operation Mode (Auth).
     *
     */
    public function testSetStationMode()
    {
    }

    /**
     * Test case for setStationPassword
     *
     * Changes the Password (Auth).
     *
     */
    public function testSetStationPassword()
    {
    }

    /**
     * Test case for setStationQrCode
     *
     * Sets the QrCode (Auth).
     *
     */
    public function testSetStationQrCode()
    {
    }
}
